/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sytoo
 */


public class Configuracoes extends javax.swing.JFrame {
    public String nome1;
    public String id1;
    public String nome_completo1;
    public String email1;
    
    /**
     * Creates new form Configuracoes
     */
    public Configuracoes(String nome, String id) {
        initComponents();
        id1 = id;
        nome1 = nome;
    }

    private Configuracoes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btAlterNome = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNome_completo = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btAPConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome Completo:");

        btAlterNome.setText("Alterar Senha");
        btAlterNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterNomeActionPerformed(evt);
            }
        });

        lblNome.setForeground(new java.awt.Color(255, 255, 255));

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));

        lblNome_completo.setForeground(new java.awt.Color(255, 255, 255));

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seus Dados");

        btAPConta.setText("Apagar Conta");
        btAPConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAPContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAPConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAlterNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btAPConta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btAlterNome))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        
       
    }//GEN-LAST:event_jPanel1FocusGained

    private void btAlterNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterNomeActionPerformed
        
            lblNome.setText(nome1);
            String driver = "org.postgresql.Driver";
            String user   = "postgres";
            String senhap = "root";
            String url      = "jdbc:postgresql://localhost:5432/qtwitter";
        
        try{

            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);
            
            int idint1 = Integer.parseInt(id1);
           
            PreparedStatement st = con.prepareStatement("select * from usuario where id = ?");
            st.setInt(1,idint1);
            
            
            ResultSet gt = st.executeQuery();
            gt.next();
            String email1 = gt.getString("email");
            String nome_completo1 = gt.getString("nome_completo");
            lblEmail.setText(email1);
            lblNome_completo.setText(nome_completo1);
            gt.close();
            con.close();
            } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado execao", "Error", JOptionPane.ERROR_MESSAGE, null);

        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE, null);

        
    }
        AlterarSenha jgg = new AlterarSenha(nome1,id1);
        jgg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btAlterNomeActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        
            lblNome.setText(nome1);
            String driver = "org.postgresql.Driver";
            String user   = "postgres";
            String senhap = "root";
            String url      = "jdbc:postgresql://localhost:5432/qtwitter";
        
        try{

            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);
            
            int idint1 = Integer.parseInt(id1);
           
            PreparedStatement st = con.prepareStatement("select * from usuario where id = ?");
            st.setInt(1,idint1);
            
            
            ResultSet gt = st.executeQuery();
            gt.next();
            String email1 = gt.getString("email");
            String nome_completo1 = gt.getString("nome_completo");
            lblEmail.setText(email1);
            lblNome_completo.setText(nome_completo1);
            gt.close();
            con.close();
            } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado execao", "Error", JOptionPane.ERROR_MESSAGE, null);

        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE, null);

        }
        
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        feedTela jgg = new feedTela(nome1,id1);
        jgg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btAPContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAPContaActionPerformed
        String driver = "org.postgresql.Driver";
        String user   = "postgres";
        String senhap = "root";
        String url    = "jdbc:postgresql://localhost:5432/qtwitter"; 
        
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);
            int idint1=  Integer.parseInt(id1);
            PreparedStatement d1 = con.prepareStatement("delete from postagem where id = ?");
            d1.setInt(1,idint1);
            d1.executeUpdate();
            
           
            PreparedStatement d2 = con.prepareStatement("delete from seguindo where id_seguindo = ? or id = ?");
            d2.setInt(1,idint1);
            d2.setInt(2,idint1);
            d2.executeUpdate();
            
            
            PreparedStatement d3 = con.prepareStatement("delete from seguidores where id_seguidor = ? or id = ?");
            d3.setInt(1,idint1);
            d3.setInt(2,idint1);
            d3.executeUpdate();
            
            
            
            PreparedStatement d4 = con.prepareStatement("delete from usuario where id = ?");
            d4.setInt(1,idint1);
            d4.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Apagado com sucesso", "OK", JOptionPane.ERROR_MESSAGE, null);
            
            con.close();
            TelaLogin tf = new TelaLogin();
            tf.setVisible(true);
            this.setVisible(false);
            
        } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado conexão", "Error", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "SQL Error", "Error", JOptionPane.ERROR_MESSAGE, null);
           
        }
    }//GEN-LAST:event_btAPContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAPConta;
    private javax.swing.JButton btAlterNome;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome_completo;
    // End of variables declaration//GEN-END:variables
}
