/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author sytoo
 */

public class feedTela extends javax.swing.JFrame {
    public String nome1;
    public String id1;
    public String id2;
    public String nome_seguir;
    /**
     * Creates new form feedTela
     */
    public feedTela(String nome, String id) {
        initComponents();
        nome1 = nome;
        id1 = id;
        
    }

    private feedTela() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        btConfig = new javax.swing.JButton();
        btSeguir = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFedd = new javax.swing.JTextArea();
        btPostar = new javax.swing.JButton();
        txtSeguir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSeg = new javax.swing.JLabel();
        btDeixar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblNome.setFont(new java.awt.Font("AvantGarde LT Medium", 2, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");

        btConfig.setText("Configurações");
        btConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigActionPerformed(evt);
            }
        });

        btSeguir.setText("Seguir");
        btSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeguirActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        txtFedd.setColumns(20);
        txtFedd.setRows(5);
        jScrollPane1.setViewportView(txtFedd);

        btPostar.setText("Publicar");
        btPostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPostarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Postagens");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nº de Seguidores");

        lblSeg.setForeground(new java.awt.Color(255, 255, 255));

        btDeixar.setText("Deixar de Seguir");
        btDeixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeixarActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btSeguir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btDeixar))
                                            .addComponent(txtSeguir)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btPostar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(lblSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btAtualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btConfig))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(200, 200, 200))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAtualizar)
                            .addComponent(btConfig))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSeguir)
                            .addComponent(btDeixar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(lblSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPostar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        String driver = "org.postgresql.Driver";
        String user   = "postgres";
        String senhap = "root";
        String url    = "jdbc:postgresql://localhost:5432/qtwitter"; 
        
        ArrayList<post> pt = new ArrayList<post>();
        ArrayList<String> pr = new ArrayList<String>();
        
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);

            
            
            PreparedStatement q1 = con.prepareStatement("select * from postagem");

            ResultSet rs = q1.executeQuery();
            while(rs.next()){
                String ids = rs.getString("id");
                String id_postes = rs.getString("id_post");
                String conteudos = rs.getString("conteudo");
                String nomes = rs.getString("nome");
                post p1 = new post();
                p1.setid(ids);
                p1.setid_post(id_postes);
                p1.setconteudo(conteudos);
                p1.setnome(nomes);
                pt.add(p1);            
            }
            rs.close();
            int sg = Integer.parseInt(id1);
            PreparedStatement q2 = con.prepareStatement("select * from seguindo where id = ?");
            q2.setInt(1,sg);
            
            ResultSet rs2 = q2.executeQuery();
            
            while(rs2.next()){
                String id = rs2.getString("id");
                String id_seguindo = rs2.getString("id_seguindo");
                String nome = rs2.getString("nome");
                pr.add(id_seguindo);
            }
            pr.add(id1);
            rs2.close();
            String feed = "";
            for (post obj1 : pt) {
                for (String obj2 : pr) {
                    if(obj1.id.equals(obj2)){
                        feed = "\n"+obj1.nome+" : "+obj1.conteudo+feed;
                    }
                }
            }
            txtFedd.setText(feed);
            
            txtFedd.setEditable(false);
            
            lblNome.setText("@"+nome1);
            
            PreparedStatement q4 = con.prepareStatement("select count(*) from seguidores where id = ?");
            q4.setInt(1,sg);
            ResultSet tg = q4.executeQuery();
            tg.next();
            String g = tg.getString(1);
            lblSeg.setText(g);
            con.close();
        } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado execao", "Error", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE, null);
        } 
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btPostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPostarActionPerformed
        Postar jg = new Postar(id1,nome1);
        jg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btPostarActionPerformed

    private void btSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeguirActionPerformed
        nome_seguir = (txtSeguir.getText());
        String driver = "org.postgresql.Driver";
        String user   = "postgres";
        String senhap = "root";
        String url    = "jdbc:postgresql://localhost:5432/qtwitter"; 
        
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);

            PreparedStatement q3 = con.prepareStatement("select id from usuario where nome LIKE ?");
            q3.setString(1,nome_seguir);
            ResultSet ry = q3.executeQuery();
            ry.next();
            id2 = ry.getString("id");
            
            
            ry.close();
            
                int idint1 = Integer.parseInt(id1);
                int idint2 = Integer.parseInt(id2);
                if(idint2 != idint1){
                PreparedStatement q4 = con.prepareStatement("INSERT INTO seguindo VALUES (?,?,?)");
                q4.setInt(1,idint1);
                q4.setInt(2,idint2);
                q4.setString(3,nome_seguir);
                q4.executeUpdate();
            
                PreparedStatement q5 = con.prepareStatement("INSERT INTO seguidores VALUES (?,?,?)");
                q5.setInt(1,idint2);
                q5.setInt(2,idint1);
                q5.setString(3,nome1);
                q5.executeUpdate();
            
                JOptionPane.showMessageDialog(rootPane, "Você esta seguindo "+nome_seguir, "OK", JOptionPane.ERROR_MESSAGE, null);

            con.close();
                }else{
        JOptionPane.showMessageDialog(rootPane, "você não pode seguir você mesmo", "Error", JOptionPane.ERROR_MESSAGE, null);
           
        }
            
        } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado conexão", "Error", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Usuario Não existe ou ja esta sendo seguido por você", "Error", JOptionPane.ERROR_MESSAGE, null);
           
        }
        
    }//GEN-LAST:event_btSeguirActionPerformed

    private void btConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigActionPerformed
        Configuracoes jgg = new Configuracoes(nome1,id1);
        jgg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConfigActionPerformed

    private void btDeixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeixarActionPerformed
        nome_seguir = (txtSeguir.getText());
        String driver = "org.postgresql.Driver";
        String user   = "postgres";
        String senhap = "root";
        String url    = "jdbc:postgresql://localhost:5432/qtwitter"; 
        
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,user,senhap);

            PreparedStatement q3 = con.prepareStatement("select id from usuario where nome LIKE ?");
            q3.setString(1,nome_seguir);
            ResultSet ry = q3.executeQuery();
            ry.next();
            id2 = ry.getString("id");
            
            
            ry.close();
            
                int idint1 = Integer.parseInt(id1);
                int idint2 = Integer.parseInt(id2);
                PreparedStatement q4 = con.prepareStatement("delete from seguindo where nome LIKE ? and id_seguindo = ?");
                q4.setString(1,nome_seguir);
                q4.setInt(2,idint2);
                q4.executeUpdate();
            
                PreparedStatement q5 = con.prepareStatement("delete from seguidores where nome LIKE ? and id_seguidor = ?");
                q5.setInt(2,idint1);
                q5.setString(1,nome1);
                int ret = q5.executeUpdate();
                if(ret == 1){
                    JOptionPane.showMessageDialog(rootPane, "você deixou de seguir "+nome_seguir, "OK", JOptionPane.ERROR_MESSAGE, null);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Você não tem "+nome_seguir+" como seguidor ou ja deixou de segui-lo", "OK", JOptionPane.ERROR_MESSAGE, null);
                    
                }
            con.close();

            
        } catch (ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nao encotrado conexão", "Error", JOptionPane.ERROR_MESSAGE, null);
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Usuario Não existe ou ja Retirado", "Error", JOptionPane.ERROR_MESSAGE, null);
           
        }
    }//GEN-LAST:event_btDeixarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin jgg = new TelaLogin();
        jgg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedTela().setVisible(true);
            }
        });
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btConfig;
    private javax.swing.JButton btDeixar;
    private javax.swing.JButton btPostar;
    private javax.swing.JButton btSeguir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSeg;
    private javax.swing.JTextArea txtFedd;
    private javax.swing.JTextField txtSeguir;
    // End of variables declaration//GEN-END:variables

}
